In [1]:
!pip install pandas matplotlib seaborn openpyxl

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (0.13.2)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in .\.venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#create employee
employee_data = {
    "Employee_ID": [101,102,103,104,105,106],
    "Employee_Name": [
        "Rahul","Priya","Amit","Sneha","Kiran","Anjali"
    ],
    "Department": [
        "AI","AI","Data Science",
        "Data Science","Python","Python"
    ],
    "Salary": [
        50000,55000,60000,
        58000,45000,48000
    ],
    "Mentor_Capacity": [
        30,35,40,35,25,30
    ]
}


employee_df = pd.DataFrame(employee_data)

employee_df

,Total_Employees,Total_Capacity,Total_Salary,Total_Students,Revenue,Capacity_Utilization_%,Profit_Loss
Department,,,,,,,
AI,2,65,105000,4,100000,6.153846,-5000
Data Science,2,75,118000,3,90000,4.000000,-28000
Python,2,55,93000,3,60000,5.454545,-33000

In [15]:
#create student
student_data = {

    "Student_ID":[1,2,3,4,5,6,7,8,9,10],

    "Course":[
        "AI","AI",
        "Data Science","Data Science",
        "Python","Python",
        "AI","Python",
        "Data Science","AI"
    ],

    "Department":[
        "AI","AI",
        "Data Science","Data Science",
        "Python","Python",
        "AI","Python",
        "Data Science","AI"
    ],

    "Fee":[
        25000,25000,
        30000,30000,
        20000,20000,
        25000,20000,
        30000,25000
    ]
}


student_df = pd.DataFrame(student_data)

student_df

   Student_ID        Course    Department    Fee
0           1            AI            AI  25000
1           2            AI            AI  25000
2           3  Data Science  Data Science  30000
3           4  Data Science  Data Science  30000
4           5        Python        Python  20000
5           6        Python        Python  20000
6           7            AI            AI  25000
7           8        Python        Python  20000
8           9  Data Science  Data Science  30000
9          10            AI            AI  25000

In [16]:
employee_analysis = employee_df.groupby(
    "Department"
).agg(

    Total_Employees=("Employee_ID","count"),

    Total_Capacity=("Mentor_Capacity","sum"),

    Total_Salary=("Salary","sum")

)


employee_analysis

              Total_Employees  Total_Capacity  Total_Salary
Department
AI                          2              65        105000
Data Science                2              75        118000
Python                      2              55         93000

In [17]:
student_analysis = student_df.groupby(
    "Department"
).agg(

    Total_Students=("Student_ID","count"),

    Revenue=("Fee","sum")

)


student_analysis

              Total_Students  Revenue
Department
AI                         4   100000
Data Science               3    90000
Python                     3    60000

In [18]:
department_analysis = employee_analysis.merge(
    student_analysis,
    on="Department"
)


department_analysis

,Total_Employees,Total_Capacity,Total_Salary,Total_Students,Revenue
Department,,,,,
AI,2,65,105000,4,100000
Data Science,2,75,118000,3,90000
Python,2,55,93000,3,60000

In [19]:
department_analysis = employee_analysis.merge(
    student_analysis,
    on="Department"
)


department_analysis

,Total_Employees,Total_Capacity,Total_Salary,Total_Students,Revenue
Department,,,,,
AI,2,65,105000,4,100000
Data Science,2,75,118000,3,90000
Python,2,55,93000,3,60000

In [20]:
department_analysis["Capacity_Utilization_%"] = (

department_analysis["Total_Students"]
/
department_analysis["Total_Capacity"]

)*100


department_analysis
department_analysis["Profit_Loss"] = (

department_analysis["Revenue"]

-

department_analysis["Total_Salary"]

)


department_analysis

,Total_Employees,Total_Capacity,Total_Salary,Total_Students,Revenue,Capacity_Utilization_%,Profit_Loss
Department,,,,,,,
AI,2,65,105000,4,100000,6.153846,-5000
Data Science,2,75,118000,3,90000,4.000000,-28000
Python,2,55,93000,3,60000,5.454545,-33000

In [1]:
def employee_suggestion(row):

    if row["Capacity_Utilization_%"] > 90:
        return "Add More Employees"

    else:
        return "No Requirement"



department_analysis["Suggestion"] = (
    department_analysis.apply(
        employee_suggestion,
        axis=1
    )
)


department_analysis

final_report = department_analysis[
[
"Total_Employees",
"Total_Students",
"Total_Capacity",
"Capacity_Utilization_%",
"Revenue",
"Total_Salary",
"Profit_Loss",
"Suggestion"
]
]


final_report

final_report.to_excel(
    "Department_Financial_Analysis.xlsx"
)

plt.figure(figsize=(10,5))


sns.barplot(
    data=department_analysis.reset_index(),
    x="Department",
    y="Total_Students",
    color="blue",
    label="Students"
)


sns.barplot(
    data=department_analysis.reset_index(),
    x="Department",
    y="Total_Capacity",
    color="orange",
    alpha=0.7,
    label="Capacity"
)


plt.title(
    "Department Student Count vs Mentor Capacity"
)

plt.ylabel("Count")

plt.legend()

plt.show()

plt.figure(figsize=(8,5))


sns.barplot(
    data=department_analysis.reset_index(),
    x="Department",
    y="Profit_Loss"
)


plt.axhline(
    0,
    color="red"
)


plt.title(
    "Department Wise Profit / Loss"
)


plt.show()

plt.figure(figsize=(8,5))


sns.barplot(
    data=department_analysis.reset_index(),
    x="Department",
    y="Capacity_Utilization_%"
)


plt.axhline(
    90,
    color="red",
    linestyle="--",
    label="Maximum Capacity"
)


plt.title(
    "Mentor Capacity Utilization Percentage"
)


plt.ylabel("Utilization %")

plt.legend()

plt.show()

NameError: name 'department_analysis' is not defined